### ISSUE TITLE
add_tag is tagging all entries

### ISSUE THREAD

**Issue by greenjesper** [logstash-plugins/logstash-filter-truncate#4]
Regardless if the field is truncated or not the tag chosen with add_tag is always added to the document.

It looks like filter_matched is always called but i assume it should only be called when the filter is matched ie. the field is truncated.

Prior to version 1.0.1 filter_matched was newer being called (resolved in #2 and #3 ) but now i seems it is always being called.

Using version 1.0.3 with the following code:
`    truncate {
      length_bytes => 32000
      fields => [ "app_message" ]
      add_tag => ["truncated"]
  }`

**Comment by guyboertje** [comment]
Unfortunately, `filter_matched` is not the best term we could have used for this mechanism.
The `add_tag` option is always executed if it is defined.

That said, a few plugins do not call `filter_matched` in error.

**Comment by guyboertje** [comment]
Some filters do indeed conditionally call filter_matched on success only.
This is not universally held to be on success for every filter though - terms of documentation and developer knowledge.
Maybe it should in the form of "Always conditionally call `filter_matched` less it **really** does not make sense not to".

**Comment by aleskovets** [comment]
Would be really useful to be able to tag document only if truncation was applied.

**Comment by crossan007** [comment]
I confirm this is an issue;  All events are subject to "add_tag" whether or not truncation occurred.

**Comment by kylemain** [comment]
I confirm this issue as well, add_tag always gets applied, no matter the result of truncate {}

**Comment by dgonzalezruiz** [comment]
I confirm this issue also applies to `add_field` parameter
